media:
  input: public/images
  output: /images
content:
  - name: posts
    label: Posts
    type: collection
    path: "src/content/blog"
    view:
      fields: [title, description, pubDate]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: pubDate
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text
