local_backend: true

backend:
  name: github
  repo: eckertalex/multilingo-club
  branch: main
  squash_merges: true
  base_url: https://sveltia-cms-auth.eckertalex.workers.dev/

media_folder: "public/images"
public_folder: "/images"

site_url: https://multilingo-club.pages.dev

logo_url: https://multilingo-club.pages.dev/favicon.svg

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/content/page"
    create: true
    delete: true
    fields:
      - name: "title"
        widget: "string"
        label: "Title"
      - name: "body"
        label: "Content"
        widget: "markdown"
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "src/content/blog"
    create: true
    delete: true
    fields:
      - name: "title"
        widget: "string"
        label: "Title"
      - name: "draft"
        widget: "boolean"
        label: "Draft"
      - name: "pubDate"
        widget: "datetime"
        label: "Publish Date"
      - name: "description"
        widget: "text"
        label: "Description"
      - name: "body"
        label: "Content"
        widget: "markdown"
  - name: "settings"
    label: "Settings"
    files:
      - label: "Site Configuration"
        name: "site-configuration"
        file: "src/content/siteConfig.json"
        editor:
          preview: false
        fields:
          - label: "Url"
            name: "site"
            widget: "hidden"
            default: "https://multilingoclub.pages.dev/"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Default locale"
            name: "locale"
            widget: "select"
            options: ["fr-FR", "en-US", "de-DE"]
            default: "en-US"
          - label: "Instagram"
            name: "socials.instagram"
            widget: "string"
            default: "https://instagram.com/"
          - label: "Navigation"
            name: "navigation"
            required: false
            widget: "list"
            default:
              - label: "Blog"
                slug: "/blog"
              - label: "A propos"
                slug: "/a-propos"
            fields:
              - label: "Label"
                name: "label"
                widget: "string"
              - label: "Slug"
                name: "slug"
                widget: "string"
