local_backend: true

backend:
  name: github
  repo: eckertalex/multilingo-club
  branch: main
  squash_merges: true
  base_url: https://sveltia-cms-auth.eckertalex.workers.dev/

publish_mode: editorial_workflow

media_folder: "public/images"
public_folder: "/images"

site_url: https://multilingo-club.pages.dev

logo_url: https://multilingo-club.pages.dev/images/logo.svg

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "src/content/blog"
    create: true
    delete: true
    fields:
      - name: "title"
        widget: "string"
        label: "Title"
      - name: "description"
        widget: "string"
        label: "Description"
      - name: "pubDate"
        widget: "datetime"
        label: "Publish Date"
      - name: "body"
        label: "Content"
        widget: "markdown"
